# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false

    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_iseparator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
    enable_filetree_gitstatus = true 

    # filetree direction
    filetree_direction = "left"

    default_shell = 'terminal'
    filemanager = "nerdtree"
  
    # auto complete
    autocomplete_method="asyncomplete"

    # snippet_engine
    snippet_engine = "ultisnips"

# Enable color theme
[[layers]]
name = 'colorscheme'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

# language server protocol
[[layers]]
name = 'lsp'
filetypes = [
  "go"
]
[layers.override_cmd]
  go = 	['gopls']

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = 'lang#markdown'

[[custom_plugins]]
  repo = "wsdjeg/mdctags.rs"

[[custom_plugins]]
  repo = "voldikss/vim-floaterm"

[[layers]]
name = 'git'

[[layers]]
name = 'lang#go'

[[layers]]
name = 'lang#python'

[[layers]]
name = 'denite'

[[layers]]
name = 'chinese'

[[layers]]
name = 'fuzzy'

[[layers]]
name = 'fzf'

[[layers]]
name = 'unite'

[[layers]]
name = 'ctrlp'

[[layers]]
name = 'tagbar'

[[layers]]
name = 'tags'

[[layers]]
name = 'lang#typescript'

[[layers]]
name = 'chat'

[[layers]]
name = 'checkers'

[[layers]]
name = 'core'

